<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-HCJ7CJO6" failures="1" tests="12" name="com.vyasa.testng.basics.DemoTestNG" time="0.082" errors="0" timestamp="2022-10-11T16:04:50 IST" skipped="2">
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase5" time="0.027"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase1" time="0.009"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase12" time="0.008"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase4" time="0.005"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase3" time="0.022">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.vyasa.testng.basics.DemoTestNG.TestCase3(DemoTestNG.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- TestCase3 -->
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase2" time="0.001">
    <skipped/>
  </testcase> <!-- TestCase2 -->
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase6" time="0.003"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase7" time="0.001"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase8" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase9" time="0.001"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase11" time="0.003"/>
  <system-out/>
  <testcase classname="com.vyasa.testng.basics.DemoTestNG" name="TestCase10">
    <skipped/>
  </testcase> <!-- TestCase10 -->
  <system-out/>
</testsuite> <!-- com.vyasa.testng.basics.DemoTestNG -->
